version: '3'

services:
  app:
    build: .
    image: mattipaksula/aszlig-hetzner
    environment:
      - HETZNER_DEV=yes
      - HETZNER_USERNAME
      - HETZNER_PASSWORD
    volumes:
      - ./app:/app
